development:
  adapter: postgresql
  encoding: unicode
  database: cfbjournal_dev
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: cfbjournal_test
  host: localhost
  pool: 5
